name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latests

    steps:
    - name: Debug Secrets
      run: |
        echo "Host: ${{ secrets.SSH_HOST }}"
        echo "User: ${{ secrets.SSH_USERNAME }}"
        echo "Port: ${{ secrets.SSH_PORT }}"
        echo "Key length: $(printf '%s' '${{ secrets.SSH_PRIVATE_KEY }}' | wc -c)"
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_mysql, xml, ctype, curl
        coverage: none

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

  deploy:
    name: Deploy to VPS
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Execute Remote SSH Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/zannatdressydolls
          git config --global --add safe.directory /var/www/zannatdressydolls
          git pull origin main
          composer install --no-dev --prefer-dist --ignore-platform-reqs
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan optimize
