name: Deploy Laravel Project

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Execute Remote SSH Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}   # <-- এখানে SERVER_USERNAME বদলে SSH_USERNAME দিন
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/zannatdressydolls
          git pull origin main
          composer install --no-dev --prefer-dist --ignore-platform-reqs
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
